VALID_RESPONSES = {
    "PH0000132": {
        "timeStamp": "27/02/2024 14:55:09",
        "busSearch": [
            {
                "id": "536827",
                "operatorId": "15229",
                "operatorName": "FIRST WEST OF ENGLAND LIMITED",
                "registrationNumber": "PH0000132/1",
                "registrationStatus": "Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH0000132",
                "licenceId": "21525",
                "licenceStatus": "Valid",
                "licenceType": "Standard National",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "X5",
                "otherServiceNumber": None,
                "variationNumber": "42",
                "startPoint": "Portishead, Combe Road",
                "finishPoint": "Cribbs Causeway, Bus Station",
                "via": "",
                "subsidised": "In Part",
                "subsidyDetail": "North Somerset Council.",
                "busServiceTypeId": "1",
                "busServiceTypeDescription": "Normal Stopping",
                "otherDetails": "To amend route and timetable on all days of operation",
                "routeDescription": "SEE FILE",
                "isShortNotice": "No",
                "localAuthorities": "Bristol City Council|North Somerset Council|South Gloucestershire Council",
                "tradingName": "FIRST",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between Portishead, Combe Road and Cribbs Causeway, Bus Station given service number X5 /  effective from 01 September 2019.",
                "contactDetailsId": "334136",
                "contactAddress1": "ENTERPRISE HOUSE",
                "contactAddress2": "",
                "contactAddress3": "",
                "contactAddress4": "BRISTOL",
                "contactPostCode": "BS5 0DZ",
                "discsInPossession": None,
                "authDiscs": "675",
                "lastModifiedOn": "25/07/2019 13:52:44",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/05/2028",
                "grantedDate": "01/06/1993",
                "effectiveDate": "01/09/2019",
                "receivedDate": "19/07/2019",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 431, "perPage": 1, "totalPages": 431},
    },
    "PH0005031": {
        "timeStamp": "27/02/2024 14:56:13",
        "busSearch": [
            {
                "id": "99588",
                "operatorId": "15055",
                "operatorName": "CHELTENHAM & GLOUCESTER OMNIBUS CO LTD",
                "registrationNumber": "PH0005031/1",
                "registrationStatus": "Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH0005031",
                "licenceId": "21351",
                "licenceStatus": "Valid",
                "licenceType": "Standard National",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "40",
                "otherServiceNumber": None,
                "variationNumber": "2",
                "startPoint": "STROUD Bus Station",
                "finishPoint": "WOTTON UNDER EDGE Memorial",
                "via": "NAILSWORTH",
                "subsidised": "No",
                "subsidyDetail": None,
                "busServiceTypeId": "1",
                "busServiceTypeDescription": "Normal Stopping",
                "otherDetails": "MONDAYS TO SATURDAYS.  1 JOURNEY PER DAY",
                "routeDescription": None,
                "isShortNotice": "No",
                "localAuthorities": "Gloucestershire County Council",
                "tradingName": "STAGECOACH WEST",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between STROUD Bus Station and WOTTON UNDER EDGE Memorial given service number 40 effective from 26-Jan-2004.",
                "contactDetailsId": "333962",
                "contactAddress1": "STAGECOACH WEST HEAD OFFICE",
                "contactAddress2": "65 LONDON ROAD",
                "contactAddress3": "",
                "contactAddress4": "GLOUCESTER",
                "contactPostCode": "GL1 3HF",
                "discsInPossession": None,
                "authDiscs": "395",
                "lastModifiedOn": "17/12/2003 09:17:52",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/08/2027",
                "grantedDate": "01/09/1992",
                "effectiveDate": "26/01/2004",
                "receivedDate": "28/11/2003",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 425, "perPage": 1, "totalPages": 425},
    },
    "PH0005985": {
        "timeStamp": "27/02/2024 14:56:45",
        "busSearch": [
            {
                "id": "137534",
                "operatorId": "14829",
                "operatorName": "EUROCOACHES LTD",
                "registrationNumber": "PH0005985/1",
                "registrationStatus": "Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH0005985",
                "licenceId": "21125",
                "licenceStatus": "Valid",
                "licenceType": "Standard International",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "N60",
                "otherServiceNumber": "N61",
                "variationNumber": "1",
                "startPoint": "BRISTOL CITY CENTRE (COLSTON STREET)",
                "finishPoint": "FILTON (NORTHVILLE)",
                "via": "STOKE GIFFORD, BRADLEY STOKE, PATCHWAY",
                "subsidised": "Yes",
                "subsidyDetail": "SOUTH GLOS COUNCIL",
                "busServiceTypeId": "1|2",
                "busServiceTypeDescription": "Limited Stop|Normal Stopping",
                "otherDetails": "SATURDAY MORNING, SUNDAY MORNING & NEW YEARS DAY MORNING:3 JOURNEYS FROM BRISTOL TO FILTON",
                "routeDescription": "FILTON, BRADLEY STOKE, PATCHWAY",
                "isShortNotice": "Yes",
                "localAuthorities": "Bristol City Council|South Gloucestershire Council",
                "tradingName": None,
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between BRISTOL CITY CENTRE (COLSTON STREET) and FILTON (NORTHVILLE) given service number N60/N61 effective from 02-May-2005.",
                "contactDetailsId": "333738",
                "contactAddress1": "DEAN ROAD",
                "contactAddress2": "",
                "contactAddress3": "",
                "contactAddress4": "BRISTOL",
                "contactPostCode": "BS37 5NH",
                "discsInPossession": None,
                "authDiscs": "100",
                "lastModifiedOn": "18/04/2005 15:58:24",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/05/2027",
                "grantedDate": "03/06/1992",
                "effectiveDate": "02/05/2005",
                "receivedDate": "15/04/2005",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 88, "perPage": 1, "totalPages": 88},
    },
    "PH1089686": {
        "timeStamp": "27/02/2024 14:57:12",
        "busSearch": [
            {
                "id": "608902",
                "operatorId": "227494",
                "operatorName": "ALTONIAN COACHES LIMITED",
                "registrationNumber": "PH1089686/1",
                "registrationStatus": "Admin Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH1089686",
                "licenceId": "369522",
                "licenceStatus": "Valid",
                "licenceType": "Standard International",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "52",
                "otherServiceNumber": None,
                "variationNumber": "2",
                "startPoint": "Bristol City Centre,Union Street",
                "finishPoint": "Imperial Park, Wills Way",
                "via": "Bedminster, Highridge",
                "subsidised": "No",
                "subsidyDetail": "",
                "busServiceTypeId": "1",
                "busServiceTypeDescription": "Normal Stopping",
                "otherDetails": "Route and timetable variation",
                "routeDescription": "",
                "isShortNotice": "Yes",
                "localAuthorities": "Bristol City Council",
                "tradingName": "TransporaBus",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between Bristol City Centre,Union Street and Imperial Park, Wills Way given service number 52 effective from 03 April 2023. To amend Route and Timetable.",
                "contactDetailsId": "680337",
                "contactAddress1": "TransporaBus",
                "contactAddress2": "Lyde Green",
                "contactAddress3": "",
                "contactAddress4": "BRISTOL",
                "contactPostCode": "BS16 7NT",
                "discsInPossession": None,
                "authDiscs": "15",
                "lastModifiedOn": "05/05/2023 12:55:41",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/08/2024",
                "grantedDate": "17/09/2009",
                "effectiveDate": "03/04/2023",
                "receivedDate": "28/03/2023",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 44, "perPage": 1, "totalPages": 44},
    },
    "PH1020951": {
        "timeStamp": "27/02/2024 14:57:40",
        "busSearch": [
            {
                "id": "155745",
                "operatorId": "161105",
                "operatorName": "STAGECOACH DEVON LTD",
                "registrationNumber": "PH1020951/1",
                "registrationStatus": "Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH1020951",
                "licenceId": "263382",
                "licenceStatus": "Valid",
                "licenceType": "Standard National",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "M",
                "otherServiceNumber": None,
                "variationNumber": "2",
                "startPoint": "EXETER BUS STATION",
                "finishPoint": "MATFORD",
                "via": "HIGH STREET",
                "subsidised": "No",
                "subsidyDetail": None,
                "busServiceTypeId": "1",
                "busServiceTypeDescription": "Normal Stopping",
                "otherDetails": "SUNDAYS ONLY EIGHT JOURNEYS IN EACH DIRECTION",
                "routeDescription": "EXETER BUS STATION TO MATFORD PARK AND RIDE VIA CITY CENTRE HIGH STREET",
                "isShortNotice": "No",
                "localAuthorities": "Devon",
                "tradingName": "STAGECOACH SOUTH WEST",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between EXETER BUS STATION and MATFORD given service number M effective from 29-Jan-2006.",
                "contactDetailsId": "575745",
                "contactAddress1": "MATFORD PARK DEPOT",
                "contactAddress2": "",
                "contactAddress3": "",
                "contactAddress4": "EXETER",
                "contactPostCode": "EX2 8FD",
                "discsInPossession": None,
                "authDiscs": "427",
                "lastModifiedOn": "01/12/2005 12:47:54",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/05/2028",
                "grantedDate": "18/06/2003",
                "effectiveDate": "29/01/2006",
                "receivedDate": "01/12/2005",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 842, "perPage": 1, "totalPages": 842},
    },
    "PH1026770": {
        "timeStamp": "27/02/2024 14:58:27",
        "busSearch": [
            {
                "id": "271277",
                "operatorId": "166812",
                "operatorName": "BUGLER COACHES LTD",
                "registrationNumber": "PH1026770/1",
                "registrationStatus": "Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH1026770",
                "licenceId": "269033",
                "licenceStatus": "Valid",
                "licenceType": "Standard National",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "965",
                "otherServiceNumber": None,
                "variationNumber": "2",
                "startPoint": "CHARLTON RD,KEYNSHAM",
                "finishPoint": "OLD DOWN,BATH",
                "via": "BITTON, OLDLAND, CADBURY HEATH,TWERTON",
                "subsidised": "No",
                "subsidyDetail": None,
                "busServiceTypeId": "6",
                "busServiceTypeDescription": "School or Works",
                "otherDetails": None,
                "routeDescription": "KEYNSHAM CHARLTON ROAD, WILLSBRIDGE- BATH ROAD",
                "isShortNotice": "Yes",
                "localAuthorities": "Bath & North East Somerset Council",
                "tradingName": None,
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between CHARLTON RD,KEYNSHAM and OLD DOWN,BATH given service number 965 effective from 01-Sep-2009.",
                "contactDetailsId": "581104",
                "contactAddress1": "TYNE DEPOT",
                "contactAddress2": "CLUTTON",
                "contactAddress3": "",
                "contactAddress4": "BRISTOL",
                "contactPostCode": "BS39 5TG",
                "discsInPossession": None,
                "authDiscs": "17",
                "lastModifiedOn": "07/09/2009 09:50:02",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/12/2028",
                "grantedDate": "19/01/2004",
                "effectiveDate": "01/09/2009",
                "receivedDate": "01/09/2009",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 38, "perPage": 1, "totalPages": 38},
    },
    "PH0006019": {
        "timeStamp": "27/02/2024 14:58:56",
        "busSearch": [
            {
                "id": "559880",
                "operatorId": "14847",
                "operatorName": "WAYNE EVANS",
                "registrationNumber": "PH0006019/1",
                "registrationStatus": "Admin Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH0006019",
                "licenceId": "21143",
                "licenceStatus": "Valid",
                "licenceType": "Standard International",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "435",
                "otherServiceNumber": None,
                "variationNumber": "2",
                "startPoint": "School Road, Brislington",
                "finishPoint": "Broadlands School, Keynsham",
                "via": "Brislington, St Annes, Broomhill",
                "subsidised": "No",
                "subsidyDetail": "",
                "busServiceTypeId": "2|6",
                "busServiceTypeDescription": "Limited Stop|School or Works",
                "otherDetails": "Timetable amendment due to Broadlands Academy changing start and finish times.",
                "routeDescription": "See file",
                "isShortNotice": "Yes",
                "localAuthorities": "Bath & North East Somerset Council|Bristol City Council",
                "tradingName": "PRIMROSE COACHES",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between School Road, Brislington and Broadlands School, Keynsham given service number 435 effective from 02 September 2020. To amend Timetable.",
                "contactDetailsId": "333756",
                "contactAddress1": "11 EAST VIEW",
                "contactAddress2": "",
                "contactAddress3": "",
                "contactAddress4": "NEWNHAM-ON-SEVERN",
                "contactPostCode": "GL14 1DG",
                "discsInPossession": None,
                "authDiscs": "4",
                "lastModifiedOn": "05/05/2023 12:53:13",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "30/06/2027",
                "grantedDate": "20/07/1992",
                "effectiveDate": "02/09/2020",
                "receivedDate": "12/08/2020",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 2, "perPage": 1, "totalPages": 2},
    },
    "PH0006633": {
        "timeStamp": "27/02/2024 14:59:21",
        "busSearch": [
            {
                "id": "311294",
                "operatorId": "14402",
                "operatorName": "BATH BUS COMPANY LTD",
                "registrationNumber": "PH0006633/1",
                "registrationStatus": "Admin Cancelled",
                "routeNumber": "1",
                "licenceNumber": "PH0006633",
                "licenceId": "20698",
                "licenceStatus": "Valid",
                "licenceType": "Standard International",
                "licenceGoodsOrPsv": "Public Service Vehicle",
                "psvDiscsToBePrintedNumber": "0",
                "serviceNumber": "Excursion",
                "otherServiceNumber": None,
                "variationNumber": "5",
                "startPoint": "BATH High Street",
                "finishPoint": "CIRCULAR",
                "via": "QUEEN SQUARE",
                "subsidised": "No",
                "subsidyDetail": None,
                "busServiceTypeId": "5",
                "busServiceTypeDescription": "Excursion or Tour",
                "otherDetails": "To revise route consequent uopn the closure of Pulteney Bridge. To operate under revised TRC provisions.",
                "routeDescription": None,
                "isShortNotice": "Yes",
                "localAuthorities": "Bath & North East Somerset Council",
                "tradingName": "BATH BUS COMPANY & CITY SIGHTSEEING",
                "trafficAreaId": "H",
                "taoCoveredByArea": "West of England",
                "publicationText": "Operating between BATH High Street and CIRCULAR given service number Excursion effective from 05-Sep-2010. To amend Route.",
                "contactDetailsId": "333316",
                "contactAddress1": "Bath Bus Company",
                "contactAddress2": "",
                "contactAddress3": "",
                "contactAddress4": "Keynsham",
                "contactPostCode": "BS31 2ED",
                "discsInPossession": None,
                "authDiscs": "60",
                "lastModifiedOn": "05/05/2023 12:53:51",
                "registrationCode": "1",
                "applicationType": None,
                "expiryDate": "31/01/2027",
                "grantedDate": "12/02/1997",
                "effectiveDate": "05/09/2010",
                "receivedDate": "23/08/2010",
                "endDate": None,
            }
        ],
        "page": {"current": 1, "totalCount": 92, "perPage": 1, "totalPages": 92},
    },
}


EXPECTED_OUTPUTS = {
    "licences": [
        {
            "licence_details": None,
            "licence_number": "NOTAVALIDLICENCE",
            "operator_details": None,
        },
        {
            "licence_details": {
                "licence_number": "PH1020951",
                "licence_status": "Valid",
                "otc_licence_id": 263382,
            },
            "licence_number": "PH1020951",
            "operator_details": {
                "operator_name": "STAGECOACH DEVON LTD",
                "otc_operator_id": 161105,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH1089686",
                "licence_status": "Valid",
                "otc_licence_id": 369522,
            },
            "licence_number": "PH1089686",
            "operator_details": {
                "operator_name": "ALTONIAN COACHES LIMITED",
                "otc_operator_id": 227494,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH1026770",
                "licence_status": "Valid",
                "otc_licence_id": 269033,
            },
            "licence_number": "PH1026770",
            "operator_details": {
                "operator_name": "BUGLER COACHES LTD",
                "otc_operator_id": 166812,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH0006633",
                "licence_status": "Valid",
                "otc_licence_id": 20698,
            },
            "licence_number": "PH0006633",
            "operator_details": {
                "operator_name": "BATH BUS COMPANY LTD",
                "otc_operator_id": 14402,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH0000132",
                "licence_status": "Valid",
                "otc_licence_id": 21525,
            },
            "licence_number": "PH0000132",
            "operator_details": {
                "operator_name": "FIRST WEST OF ENGLAND " "LIMITED",
                "otc_operator_id": 15229,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH0006019",
                "licence_status": "Valid",
                "otc_licence_id": 21143,
            },
            "licence_number": "PH0006019",
            "operator_details": {
                "operator_name": "WAYNE EVANS",
                "otc_operator_id": 14847,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH0005985",
                "licence_status": "Valid",
                "otc_licence_id": 21125,
            },
            "licence_number": "PH0005985",
            "operator_details": {
                "operator_name": "EUROCOACHES LTD",
                "otc_operator_id": 14829,
            },
        },
        {
            "licence_details": {
                "licence_number": "PH0005031",
                "licence_status": "Valid",
                "otc_licence_id": 21351,
            },
            "licence_number": "PH0005031",
            "operator_details": {
                "operator_name": "CHELTENHAM & GLOUCESTER " "OMNIBUS CO LTD",
                "otc_operator_id": 15055,
            },
        },
    ]
}

VALID_AUTH_RESPONSE = {
    "token_type": "Bearer",
    "expires_in": 3599,
    "ext_expires_in": 3599,
    "access_token": "DummyToken"
}
