name: Build on CI
on:
  push:
    branches-ignore:
        - main

permissions: read-all

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: frontend/.nvmrc

      - name: Install
        run: npm i

      - name: Check types
        if: success() || failure()
        run: npm run tsc:build

      - name: Run linters
        if: success() || failure()
        run: npm run lint

      - name: Run tests
        if: success() || failure()
        run: npm run test

      - name: build frontend code
        if: success() || failure()
        run: |
          npm install
          npm run build

  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: "0"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: setup sam
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run tests
        if: success() || failure()
        run: pytest

      - name: build backend code
        if: success() || failure()
        run: |
          sam build
